config/routes.rb
Rails.application.routes.draw do

	# get '/listings' => 'listings#index'
	# get 'listings/new' => 'listings#new'

  
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :listings do
  	resources :photos
  end

  resources :users 
  resources :messages
  get '/deletemessages' => 'messages#destroy'

  #root page
  root to: 'application#index'

end

app/models/listing.rb
class Listing
  include Mongoid::Document
  field :type, type: String
  field :address, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: Integer
  field :num_bed, type: Integer
  field :num_bath, type: Integer
  field :price, type: Integer
  field :description, type: String
  field :available_date, type: Date
  field :latitude, type: Float
  field :longitude, type: Float
  field :parking, type: Boolean
  field :pets, type: Boolean
  field :furnished, type: Boolean
  field :acheater, type: Boolean
  field :privatebath, type: Boolean
  field :wifi, type: Boolean
  mount_uploader :photo, ListingPhotoUploader
  embeds_many :photos
  belongs_to :user
  

 	validates :type, presence: true
  validates :city, presence: true
  validates :num_bed, presence: true
  validates :num_bath, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :available_date, presence: true

  def full_address
    return "#{address}, #{city}, #{state}, #{zip}"
  end
end

app/models/message.rb
class Message
  include Mongoid::Document
  field :subject
  field :sender
  field :body
  field :senderid
  belongs_to :user
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  field :url, type: String
  mount_uploader :photo, ListingPhotoUploader
  embedded_in :listing
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :email, type: String
  field :password_digest, type: String
  field :firstname
  field :lastname
  field :phonenumber
  field :occupation
  field :bio
  field :age
  field :personality
  has_many :listings
  has_many :messages

  has_secure_password

  validates :email, uniqueness: true
  validates :password, confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def index
  end

  def current_user
  	@current_user ||= User.find(session[:user_id]['$oid']) if session[:user_id]
  end

  def authorize
  	unless current_user
  		redirect_to login_path
  	end
  end
  
  def login
    if current_user
      redirect_to listings_path
    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController


  def index
    # city search function for the listings 
    if params[:search]
      @listings = Listing.where(:city => params[:search].downcase)
    else
      @listings = Listing.all
    end
  end

  def show
      @listing = Listing.find(params[:id])
      @user = User.find(@listing.user_id)
  end


  def create
      @listing = current_user.listings.new(listing_params)
      
      # getting the latitude & the longitude using geokit gem/Geocoder to request geocode of the address entered, used to display pin on map
      @listing.latitude = Geokit::Geocoders::GoogleGeocoder.geocode(@listing.full_address).latitude
      @listing.longitude = Geokit::Geocoders::GoogleGeocoder.geocode(@listing.full_address).longitude
      
      @listing[:city].downcase!

    if @listing.save
      flash[:success] = "Listing created!"
      redirect_to listings_path
    else
      flash[:danger] = "All Fields are Required"
      render :new
    end
  end

  def edit
      @listing = Listing.find(params[:id])
  end
  
  def update
      #saves update listing
      @listing = Listing.find(params[:id])
  
    if @listing.update(listing_params)
      redirect_to listing_path
    else
      render :edit
    end
  end
  
  def destroy
      @listing = Listing.find(params[:id])
     
      @listing.destroy
     
      redirect_to listings_path
  end

  private
  
  def listing_params
      params.require(:listing).permit(:type, :address, :city, :state, :zipcode, :num_bed, :num_bath, :price, :description, :available_date, :photo, :latitude, :longitude, :parking, :pets, :acheater, :privatebath, :wifi, :furnished)
  end
  
  end 

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
   @messages = current_user.messages.all
  end

  def new
    @message= Message.new
  end
  
  def create
    @message = Message.new(params.require(:message).permit(:sender,:senderid,:subject,:user_id,:body))
    @message.sender = current_user.firstname
  
    if @message.save
      redirect_to user_path(@message.user) 
    else
      redirect_to listings_path 
    end
  
  end
  
  def destroy
        Message.find(params[:param1]).destroy
        redirect_to messages_path 
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def new
		@listing = Listing.find(params[:listing_id])
	  @photo = Photo.new
	end

	def create
		# adding new photo to the listing / pushing new photo to the photo array
		@listing = Listing.find(params[:listing_id])
	  @listing.photos.push( Photo.new(params.require(:photo).permit(:photo)) )
	  if @listing.save
	  	redirect_to listing_path(@listing)
	  end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :login, except: [:destroy]
	def new
	end

	def create
		#user authentication required/added flash messages.
		user = User.find_by(email: params[:user][:email])
		if user && user.authenticate(params[:user][:password])

			flash[:success] = "Login Successful"
			session[:user_id] = user.id
			redirect_to listings_path
		else
			flash.now[:danger] = "Unable to Login, Please try again!"
			render :new
		end
	end

	def destroy
		#redirects to login page after user logs off
		session[:user_id]= nil
		redirect_to login_path
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 before_action :authorize, :only => [:show, :edit, :update]
	def new
		@user = User.new
	
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		#creates a user, after user signs up, redirects to login page.
		@user = User.new(params.require(:user).permit(:username, :firstname, :lastname, :occupation, :phonenumber, :email, :age, :personality, :bio, :password, :password_confirmation))
		
		if @user.save
                        session[:user_id] = @user.id
			redirect_to listings_path 
		else 
			redirect_to new_user_path
		end
	end

	def edit
      @user = User.find(params[:id])
  	end

  	def update
      @user = User.find(params[:id])

     if @user.update(params.require(:user).permit(:username, :firstname, :lastname, :occupation, :phonenumber, :email, :age, :personality, :bio, :password, :password_confirmation))
      redirect_to user_path(current_user)
     else
      render :edit
     end
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/index.html.erb
<!-- Landing Page with three slides-->
    
<!-- only showing first carousel page as landing page for now -->
<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="5000" id="bs-carousel">
  <!-- Overlay -->
  <div class="overlay"></div>

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#bs-carousel" data-slide-to="1"></li>
    <!-- <li data-target="#bs-carousel" data-slide-to="2"></li> -->
  </ol>
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner">

    <div class="item slides active">
      <div class="slide-1">
        <div class="hero"> 
          <hgroup>
            <h1>Find A Roommate</h1>   <br><br>     
            <%= form_tag listings_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search], :placeholder => "Where Do You Want to Live?", :style =>"color: black;" %><br><br>
            <%= submit_tag "Take Me There", :class => "btn btn-hero btn-lg" %>
            <% end %>
          </hgroup>       
        </div>
      </div>
    </div>

    <div class="item slides">
      <div class="slide-2">
        <div class="hero">
          <hgroup>
            <h1>Post your Space</h1>        
          </hgroup>
          <%= button_to "Login", login_path,
          :class => "btn btn-hero btn-lg", :method => :get %>
        </div>
      </div>
    </div>

  <!--   <div class="item slides">
      <div class="slide-3">
        <div class="hero">   
          <hgroup>
            <h1>Meet Your Future Roommate(s)</h1>        
          </hgroup>  
          <%#= button_to "Meet Our Members", new_user_path,
          :class => "btn btn-hero btn-lg", :method => :get %>     
        </div>
      </div>
    </div> -->

  </div>
</div>

<!-- <div class="info">
  <div class="col-md-4">
  <h2>How It Works</h2>
  <i class="fa fa-lightbulb-o fa-lg"></i><br>
  <p class="divider">----------------------</p>
    <p class="info-landing">Sign up, tell us where you want to live. <br> Found a place you like?<br> Start a conversation, <br> get ready to move!</p>
    <p class="divider">----------------------</p>
  </div>
  <div class="col-md-4">
    <h2>Why Nested</h2>
    <i class="fa fa-question fa-lg"></i><br>
    <p class="divider">----------------------</p>
    <p class="info-landing">Payment system? <br> In app agreement drafts?<br> Review feature? <br>All currently in the making!</p>
    <p class="divider">----------------------</p>
  </div>
  <div class="col-md-4">
    <h2>Contact Us</h2>
    <i class="fa fa-envelope-o"></i><br>
    <p class="divider">----------------------</p>
    <p class="info-landing">Our aim is to make Nested the best housing and roommate search tool on the market. <br>Have something to say? <br> Help us make Nested better? <br> Drop us a message!</p>
    <p class="divider">----------------------</p>
  </div>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nested</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Oxygen:300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAtMTyEHjwug0bqEL-IEuEKgW3paGNZ0Jk" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- navigation bar -->

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">
          <img src="http://i2.photobucket.com/albums/y23/maggiewang430/Logo_zps875a4da5.png" id="logo">
          </a>
        </div>
        
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li><p class="greeting">Welcome back, <%= current_user.firstname %> <%= link_to "Edit Profile", edit_user_path(current_user.id) %></p></li>
          <a type="button" class="btn btn-warning navbar-btn navbar-right" href="/logout">Log Out</a>
        </ul>
        <ul class="nav navbar-nav navbar-left">
          <a type="button" class="btn btn-success navbar-btn navbar-left" href="#" data-toggle="modal" data-target="#basicModal">Post Your Space</a>
           <a type="button" class="btn btn-info navbar-btn navbar-right" href="/listings">All Listings</a>
           <a type="button" class="btn btn-warning navbar-btn navbar-left" href="/messages"> Messages</a>

          <%= render 'listings/listing_modal' %>
          <% else %>
          <li><p class="greeting"><%= link_to "Log In", '/login' %></p></li>
          
          <a type="button" class="btn btn-warning navbar-btn navbar-right" href="#" data-toggle="modal" data-target="#basicModal">Join nested</a>
          <%= render 'users/user_modal' %>
          <% end %>
        </ul>
      </div>
    </nav>

  



    


  <!-- user sees add listing link if logged in -->

   

  <%= yield %>

 
  

</body>

</html>

app/views/listings/_form.html.erb
<!-- listing form -->

<div class="form-group-listing">

  <%= form_for Listing.new() do |f| %>

  <%= f.select :type, options_for_select(["House", "Condo", "Townhouse", "Apartment", "Roomshare", "Studio", "Sublet", "Roomshare"])%><br>
  <br>
  <%= f.text_field :address, :placeholder=>"Address" %><br>
  <br>
  <%= f.text_field :city, :placeholder=>"City" %><br>
  <br>
  State <%= f.select :state, options_for_select(['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'])  %>
  <%= f.text_field :zip, :placeholder=>"Zipcode" %><br><br>
  Bedrooms &nbsp;<%= f.select :num_bed, options_for_select([0, 1, 2, 3, 4, 5, 6, 7])%><br><br>
  Bathrooms &nbsp;<%= f.select :num_bath, options_for_select([0, 1, 2, 3, 4, 5, 6, 7])%><br><br>
  $ <%= f.number_field :price, :placeholder=>"How Much is Rent?" %><br><br>
  Date Available: 
  <%= f.date_field :available_date %>      <br>
  Parking &nbsp; <%= f.check_box :parking %>&nbsp;&nbsp;
  AC/Heater: &nbsp;<%= f.check_box :acheater %> &nbsp;&nbsp;
  Pets Allowed: &nbsp; <%= f.check_box :pets %> <br>
  Furnished &nbsp;<%= f.check_box :furnished %> &nbsp;&nbsp;
  Private Bath &nbsp;<%= f.check_box :privatebath %> &nbsp;&nbsp;
  Wifi &nbsp;<%= f.check_box :wifi %>                <br><br>
  Description: <br>
  <%= f.text_area :description, :placeholder=>"Tell us a bit about the place." %><br>
  6 Photos Minimum 

  <span style:"padding-left: 200px"><br><%= f.file_field :photo %><br></span>
  
  <%= f.submit 'Create Listing', :class => "btn btn-info" %>
  
  <% end %>

</div>

app/views/listings/_individual_map.html.erb
<!-- individual map -->

<script type="text/javascript">
  function initialize() {
    var myLatlng;
          // The current zoom and location of where the map is centerd on
          navigator.geolocation.getCurrentPosition(function(position) {
            myLatlng =(new google.maps.LatLng(<%= @listing.latitude %>, <%= @listing.longitude %>));
            console.log(myLatlng);

            var mapOptions = {
              zoom: 16,
              center: myLatlng
            }

          // Create a map with a canvas
          var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);


          // The function to create a longitude and latitude in Google Maps
          function makeLatLng(latitude, longitude) {
            return new google.maps.LatLng(latitude, longitude)
          }

          //The function to create a marker in Google Maps
          function makeMarker(latitude, longitude) {
            return new google.maps.Marker({
              position: makeLatLng(latitude, longitude),
              map: map,
              icon:'http://i2.photobucket.com/albums/y23/maggiewang430/house-icon-dark-green-hi_zps900cbd67.png'
            });
          }

          // Add saved longitudes and latitudes to save on the map

          var <%= "marker" + @listing.id %> = makeMarker(<%= @listing.latitude %>, <%= @listing.longitude %>);
          
          var <%= "infoWindow" + @listing.id %> = new google.maps.InfoWindow({
            content: '<span><strong>Address:</strong> <%= @listing.address %></span><br> <span><%= @listing.city %>, <%= @listing.state %> <%= @listing.zip %></span><br> <span><strong>Type:</strong> <%= @listing.type %></span><br> <span><strong>Bedroom:</strong> <%= @listing.num_bed %></span><br> <span><strong>Bathroom:</strong> <%= @listing.num_bath %></span><br> <span><strong>Price:</strong> <%= @listing.price %></span><br> <span><strong>Description:</strong> <%= @listing.description %></span> <br> <span><strong>Photos:</strong> <%= image_tag @listing.photo.url, height: '150', width: '130' %></span>'
          });

          google.maps.event.addListener(<%= "marker" + @listing.id %>, 'click', function() {
            <%= "infoWindow" + @listing.id %>.open(map,<%= "marker" + @listing.id %>);
            setTimeout(function(){ <%= "infoWindow" + @listing.id %>.close(map,<%= "marker" + @listing.id %>); }, 5000);
          });

        });

}

        // Loads Google Map on window load
        google.maps.event.addDomListener(window, 'load', initialize);
      </script>

app/views/listings/_listing_modal.html.erb
<!-- modal for listing -->
<div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <p class="modal-title legend" id="myModalLabel">Tell Us About Your Place</p>
      </div>
      <div class="modal-body">
        <%= render 'listings/form' %>
      </div>
    </div>
  </div>
</div>

app/views/listings/_map.html.erb
<!-- main map for listing page -->

<script type="text/javascript">
        function initialize() {
        var myLatlng;
          // The current zoom and location of where the map is centerd on
          navigator.geolocation.getCurrentPosition(function(position) {
            myLatlng =(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
            console.log(myLatlng);
      
          var mapOptions = {
            zoom: 11,
            center: myLatlng
          }

          // Create a map with a canvas
          var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);


          // The function to create a longitude and latitude in Google Maps
          function makeLatLng(latitude, longitude) {
            return new google.maps.LatLng(latitude, longitude)
          }

          //The function to create a marker in Google Maps
          function makeMarker(latitude, longitude) {
            return new google.maps.Marker({
              position: makeLatLng(latitude, longitude),
              map: map,
              icon:'http://i2.photobucket.com/albums/y23/maggiewang430/5734948b-ced6-4447-8e48-d4dc820d1f4a_zpsf5729f8e.png'
            });
          }

          // Add saved longitudes and latitudes to save on the map
          <% @listings.each do |listing| %>

          var <%= "marker" + listing.id %> = makeMarker(<%= listing.latitude %>, <%= listing.longitude %>);
          
          var <%= "infoWindow" + listing.id %> = new google.maps.InfoWindow({
            content: '<span><strong>Address:</strong> <%= listing.address %></span><br> <span><%= listing.city %>, <%= listing.state %> <%= listing.zip %></span><br> <span><strong>Type:</strong> <%= listing.type %></span><br> <span><strong>Bedroom:</strong> <%= listing.num_bed %></span><br> <span><strong>Bathroom:</strong> <%= listing.num_bath %></span><br> <span><strong>Price:</strong> <%= listing.price %></span><br> <span><strong>Description:</strong> <%= listing.description %></span>'
          });

          google.maps.event.addListener(<%= "marker" + listing.id %>, 'click', function() {
            <%= "infoWindow" + listing.id %>.open(map,<%= "marker" + listing.id %>);
            setTimeout(function(){ <%= "infoWindow" + listing.id %>.close(map,<%= "marker" + listing.id %>); }, 2000);
          });
          <% end %>

        });

        }

        // Loads Google Map on window load
        google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/listings/edit.html.erb
  <!-- form for editing a listing -->
  <form>
    <%= form_for @listing do |f| %>

    Type: <%= f.text_field :type %><br>
    City: <%= f.text_field :city %><br>
    Bedrooms: <%= f.number_field :num_bed %><br>
    Bathrooms: <%= f.number_field :num_bath %><br>
    Rent: $ <%= f.number_field :price %><br>
    Parking <%= f.check_box :parking %>      <br>
    AC/Heater <%= f.check_box :acheater %>    <br>
    Pets: <%= f.check_box :pets %><br>
    Furnished <%= f.check_box :furnished %>    <br>
    Private Bath <%= f.check_box :privatebath %> <br>
    Wifi <%= f.check_box :wifi %>
    Description: <%= f.text_area :description %><br>
    Listing Thumbnail <%= f.file_field :photo, :multiple => true %></br><br>
    <br>
    <%= f.submit 'Update' %>
    
    <% end %>
  </form>

app/views/listings/index.html.erb
<!-- index map view for when user is logged in -->
<div class="col-md-8 maps">
  <div id="map-container">
    <div id="map-canvas">
      <%= render 'map' %>
    </div>
  </div>
</div>

<!-- listing info view for logged in users -->
 <div class="col-md-4 listings">
    <div class='ovaflowing'>
      <% @listings.each do |f| %>
        <div class="listing-each">
          <p><%= f.type %> | <%= f.address %>, <%= f.city.capitalize %>, <%= f.state %> <%= f.zip %> | Bedrooms: <%= f.num_bed %> | Bathrooms: <%= f.num_bath %> | $<strong><%= f.price %></strong></p>
          <p><%= link_to 'More', listing_path(f), :class => "btn btn-info btn-sm" %></p> 
          
<!--           <p><%#=  image_tag f.photo.url(:small), height: '90', width: '80' %></p> --> 
        </div>
     <% end %>
    </div>

 </div>


    <!-- listing info view for not logged in users -->
      
       <!--  <table>
          <tbody>
            <table class="table table-hover">
              <%# @listings.each do |f| %>
              <tr>
                  <td><%#= f.type %></td>
                  <td><%#= f.address %></td>
                  <td><%#= f.city.capitalize %> 
                  <td><%#= f.state %></td>
                  <td><%#= f.zip %></td>
                  <td><%#= f.num_bed %></td>
                  <td><%#= f.num_bath %></td>
                  <td>$<#%= f.price %></td>
                  <td><%#= f.description %></td>
                  <td><%#= image_tag f.photo.url(:small), height: '150', width: '130' %></td>
                  <%#if current_user %>
                  <td><%#= link_to 'See More', listing_path(f), :class => "btn btn-info" %></td>
                  <%# else %>
                  <td><%#= link_to "Login to see more", login_path, :class => "btn btn-info" %></td>
                  <%# end %>
                </tr>
                <%# end %>
              </table>
            </tbody>
          </table>
          <%#end%>
  
  </div>
</div>

app/views/listings/new.html.erb
<!-- add listing page view -->

<%= render 'listings/form' %>

app/views/listings/show.html.erb
<!-- view page for individual listings -->
<!-- map for individual listing page -->
<div class="col-md-6 maps">
	<div id="map-container">
		<div id="map-canvas">
			<%= render 'individual_map' %>
		</div>
	</div>
</div>

<div class="col-md-6 listings">
	<!-- <div class="form-group"> -->
	<!-- Type: <%#= @listing.type %> <br>
	Price: $ <%#= @listing.price %><br>
	Bedrooms: <%#= @listing.num_bed %>
	Bathrooms: <%#= @listing.num_bath %><br>
	Pets:<%# if @listing.pets == true %> OK <%# else %> NOT ALLOWED <%# end %><br>
	Description: <%#= @listing.description %><br>
	Date Available: <%#= @listing.available_date %>
	Address: <br>
	<%#= @listing.address %><br>
	<%#= @listing.city %>, <%#= @listing.state %><%#= @listing.zip %><br><br> -->

	<!-- </p>
	Photos: <br> <%#= image_tag @listing.photo.url, height: '150', width: '130' %><br><br> -->

	<!-- </div> -->

	<div class="galleria" style="height: 500px; width: 600px; z-index: 99; position: relative;">
		<% @listing.photos.each do |p| %>
		<%= image_tag p.photo.url, height: '150', width: '130' %>
		<% end %>
		<script>
			Galleria.loadTheme('https://cdnjs.cloudflare.com/ajax/libs/galleria/1.4.2/themes/classic/galleria.classic.js');
			Galleria.run('.galleria');
		</script>
	</div>
	<%#= link_to "Delete this photo", :class => "btn btn-default" %>
	<!-- listed by user info section -->
	<div class="lister">
		<p class="listed-by"> Listed by
		<%= @user.firstname %>  <%= @user.lastname %> 
		<% if current_user %>
		<%= @user.phonenumber %> 
		<%= @user.email %> 
		<%= link_to "View Profile", user_path(@user.id) %>
		<% else %>
		<br></p>
		Login to Send <%= @user.firstname %> a Message
		<% end %>
	</div>
	<!-- editing options for logged in user -->
	
	<div class="form-group">
		<% if current_user %>
		<% if  @listing.user.id == current_user.id %>
		<%= link_to "Add Photos", new_listing_photo_path(@listing), :class => "btn btn-info" %>
		<%= link_to "Manage Listing", edit_listing_path, :class => "btn btn-warning" %>
		<%= link_to "Delete listing", :listing, method: :delete, data: { confirm: "Are you sure you want to delete this listing?"},  :class => "btn btn-danger" %>
		<% else %>
		<%= link_to "Back to the list", listings_path, :class => "backbutton btn btn-info" %>
		<% end %>
		<% end %>
	</div>
	
</div>

app/views/messages/index.html.erb
<!-- messaging feature -->

<div class="message-view">
<% @messages.each do |v| %> <br>
<h4>Sent by : <%= link_to "#{v.sender}", user_path(v.senderid) %></h>
<h4>Subject: <%= v.subject %></h4>
<br>
<br>
<%= v.body %>
<br>
<br>
<%= form_for Message.new() do |f| %>
<div id = 'hidden'>
	<%= f.text_field :sender, :value => current_user.firstname + current_user.lastname %>
	<%= f.text_field :senderid, :value => current_user.id %>
	<%= f.text_field :user_id, :value => v.senderid %>
</div><br>
Subject:  <%= f.text_field :subject, :value => "Re: #{v.subject}" %>
<br>
<br>
Body <%= f.text_field :body, :value => "" %>
<br><br>
<%= f.submit 'reply' %>
<% end %>
<br>
<%= link_to "delete", "/deletemessages?param1=#{v.id}&param2=#{v.id}" %>

<% end %>
</div>

app/views/photos/new.html.erb
<!-- photo upload page view -->
<%= form_for [@listing, @photo] do |f| %>
	<%= f.file_field :photo %>
	<%= f.submit 'Add Photo', :class => "btn btn-info" %>
<% end %>

app/views/users/_form.html.erb
<!-- sign up page view -->

<div class="new-user">
	<!-- <h1 style="color: tomato">Join Us</h1>  -->
	<%= form_for User.new() do |f| %>
	
	First Name<br> <%= f.text_field :firstname %><br>
	Last Name<br> <%= f.text_field :lastname %><br>
	Phone<br> <%= f.text_field :phonenumber %><br>
	Email <br><%= f.text_field :email %><br>
	Occupation<br> <%= f.text_field :occupation %><br>
    Select Your Age <br> <%= f.select :age, options_for_select(['18-25','26-35','35+']) %> <br>
	Password <br> <%= f.password_field :password %><br>
	Confirm Your Password <br><%= f.password_field :password_confirmation %><br><br>
	<%= f.submit "Join", :class => "btn btn-info" %>
	<% end %>
	
</div>

app/views/users/new.html.erb
<!-- add listing page view -->

<%= render 'users/form' %>